pragma Singleton

import Quickshell
import Quickshell.Io
import Quickshell.Hyprland
import QtQuick
import qs.config
import qs.services

Singleton {
  id: root
  property var monitors: []
  property bool loading: false
  property bool applying: false
  property bool saving: false
  property bool persistenceAvailable: false
  readonly property string configFormat: Hyprland.usingLua ? "lua" : "conf"
  property string configDirectory: Config.monitorConfigDirectory
  property var _lastEdits: []
  property bool _pendingVerify: false
  property bool refreshPending: false
  property string queryError: ""

  signal monitorsLoaded()
  signal applyDone(bool hasErrors, string errorText)
  signal persistDone(bool hasErrors, string errorText)

  function findCurrentMode(m) {
    const target      = `${m.width}x${m.height}`;
    const rateRounded = Math.round(m.refreshRate);
    return (m.availableModes || []).find(mode => {
      const match = mode.match(/^(\d+x\d+)@([\d.]+)Hz$/);
      return match
        && match[1] === target
        && Math.round(parseFloat(match[2])) === rateRounded;
    }) ?? (m.availableModes || [])[0]
      ?? `${m.width}x${m.height}@${m.refreshRate.toFixed(2)}Hz`;
  }

  // Themes core: builds one monitor line with a caller-supplied prefix
  // ("keyword monitor " for hyprctl, "monitor=" for monitors.conf)
  function buildMonitorLine(m, prefix) {
    if (m.disabled) return `${prefix}${m.name},disable`;
    const parsed = MonitorUtils.parseMode(m.selectedMode);
    const res  = parsed ? `${parsed.w}x${parsed.h}` : `${m.width}x${m.height}`;
    const rate = parsed ? parsed.rate : m.refreshRate.toFixed(2);
    let line = `${prefix}${m.name},${res}@${rate},${m.x}x${m.y},${m.scale}`;
    if (m.transform !== 0) line += `,transform,${m.transform}`;
    if (m.mirrorOf  !== "") line += `,mirror,${m.mirrorOf}`;
    return line;
  }

  function buildMonitorArg(m) {
    return buildMonitorLine(m, "keyword monitor ");
  }

  function buildFileContent(edits) {
    const lines = ["# Generated by Quickshell MonitorManager"];
    for (const m of edits) lines.push(buildMonitorLine(m, "monitor="));
    return lines.join("\n") + "\n";
  }

  // Lua equivalent of buildMonitorLine/buildFileContent, used when hyprland.lua is active.
  function buildMonitorLuaLine(m) {
    if (m.disabled) return `hl.monitor({ output = ${JSON.stringify(m.name)}, disabled = true })`;
    const parsed = MonitorUtils.parseMode(m.selectedMode);
    const res  = parsed ? `${parsed.w}x${parsed.h}` : `${m.width}x${m.height}`;
    const rate = parsed ? parsed.rate : m.refreshRate.toFixed(2);
    let fields = `output = ${JSON.stringify(m.name)}, mode = "${res}@${rate}", position = "${m.x}x${m.y}", scale = ${m.scale}`;
    if (m.transform !== 0) fields += `, transform = ${m.transform}`;
    if (m.mirrorOf  !== "") fields += `, mirror = ${JSON.stringify(m.mirrorOf)}`;
    return `hl.monitor({ ${fields} })`;
  }

  function buildFileContentLua(edits) {
    const lines = ["-- Generated by Quickshell MonitorManager"];
    for (const m of edits) lines.push(buildMonitorLuaLine(m));
    return lines.join("\n") + "\n";
  }

  function refresh() { refreshDebounce.restart(); }

  function normalize(raw) {
    if (!Array.isArray(raw)) throw new Error("Invalid monitor response");
    return raw.map(m => ({
      name: m.name, description: m.description || "", width: m.width, height: m.height,
      x: m.x, y: m.y, selectedMode: root.findCurrentMode(m), scale: m.scale,
      refreshRate: m.refreshRate, transform: m.transform || 0, disabled: !!m.disabled,
      mirrorOf: (() => {
        if (!m.mirrorOf || m.mirrorOf === "none") return "";
        const id = Number(m.mirrorOf);
        return Number.isFinite(id) ? raw.find(other => other.id === id)?.name ?? "" : m.mirrorOf;
      })(),
      availableModes: m.availableModes || []
    }));
  }

  function query(callback) {
    loading = true;
    HyprlandClient.request("j/monitors all", (text, error) => {
      try {
        if (error) throw new Error(error);
        monitors = normalize(JSON.parse(text));
        queryError = "";
      } catch (e) { queryError = String(e); }
      loading = false;
      if (!queryError) monitorsLoaded();
      callback(queryError);
    });
  }

  function _doRefresh() {
    if (loading || applying) { refreshPending = true; return; }
    refreshPending = false;
    query(error => {
      if (error) console.warn("Could not read monitors:", error);
      if (refreshPending) refresh();
    });
  }

  function apply(edits) {
    if (applying || saving) return;
    applying = true;
    _lastEdits = edits.map(m => Object.assign({}, m));
    const command = "[[BATCH]]" + _lastEdits.map(buildMonitorArg).join(" ; ");
    HyprlandClient.request(command, (text, error) => {
      const errors = text.split("\n").map(s => s.trim()).filter(s => s !== "" && s !== "ok");
      if (error || errors.length > 0) {
        finishApply(error || errors.join("; "));
        return;
      }
      // Always enqueue a NEW read after the apply reply. An older poll is not verification.
      _pendingVerify = true;
      query(queryError => finishApply(queryError || verifyApply()));
    });
  }

  function verifyApply() {
    const mismatches = [];
    for (const edit of _lastEdits) {
      const live = monitors.find(m => m.name === edit.name);
      if (!live) { mismatches.push(edit.name + ": not found after apply"); continue; }
      if (live.disabled !== edit.disabled) mismatches.push(edit.name + ": enabled state did not apply");
      if (edit.disabled) continue;
      const expectedMode = MonitorUtils.parseMode(edit.selectedMode);
      if (!expectedMode || live.width !== expectedMode.w || live.height !== expectedMode.h
          || Math.abs(live.refreshRate - expectedMode.rate) > 0.1)
        mismatches.push(edit.name + ": mode did not apply");
      for (const key of ["x", "y", "transform", "mirrorOf"])
        if (live[key] !== edit[key]) mismatches.push(edit.name + ": " + key + " did not apply");
      if (Math.abs(live.scale - edit.scale) > 0.001) mismatches.push(edit.name + ": scale did not apply");
    }
    return mismatches.join("; ");
  }

  function finishApply(error) {
    _pendingVerify = false;
    applying = false;
    applyDone(error !== "", error);
    if (refreshPending) refresh();
  }

  function persistToFile(edits) {
    if (saving) return;
    saving = true;
    savedConfig.write(configDirectory + "/monitors." + configFormat,
      configFormat === "lua" ? buildFileContentLua(edits) : buildFileContent(edits));
  }

  TextFileWriter {
    id: savedConfig
    onCompleted: (success, error) => {
      root.saving = false;
      root.persistDone(!success, success ? "" : "Display settings applied, but could not save: " + error);
    }
  }
  FileView {
    id: sourceConfig
    path: root.configDirectory + "/hyprland." + root.configFormat
    blockLoading: false
    printErrors: false
    watchChanges: true
    onFileChanged: reload()
    onLoaded: {
      const content = text().split("\n").filter(line => !line.trim().startsWith(root.configFormat === "lua" ? "--" : "#")).join("\n");
      root.persistenceAvailable = root.configFormat === "lua"
        ? /require\s*\(?\s*["']monitors["']/.test(content)
        : /^\s*source\s*=.*monitors\.conf\s*(?:#.*)?$/m.test(content);
    }
    onLoadFailed: root.persistenceAvailable = false
  }
  Timer { id: refreshDebounce; interval: Config.monitorRefreshDebounce; onTriggered: root._doRefresh() }
  Connections {
    target: Hyprland
    function onRawEvent(event) {
      if (["monitoradded", "monitorremoved", "configreloaded"].includes(event.name)) {
        if (event.name === "configreloaded") sourceConfig.reload();
        root.refresh();
      }
    }
  }
}
